[install]
dev = true
peer = true
optional = true
frozenLockfile = false
saveTextLockfile = true
linker = "hoisted"

[install.cache]
dir = ".cache/bun"
disable = false
disableManifest = false

[install.lockfile]
save = true

[runtime]
node = true
