-- Seed data for portfolios table
-- This script runs after database initialization

USE portfolio;

-- Insert sample portfolio data (20 portfolios)
INSERT INTO `portfolios` (`id`, `title`, `slug`, `company`, `date`, `current`, `overview`, `description`, `content`, `thumbnail_temp`, `intro`, `created_at`, `updated_at`)
VALUES
    (
        '30000000-0000-0000-0000-000000000001',
        'E-Commerce Platform',
        'e-commerce-platform',
        'Example Company',
        DATE_SUB(NOW(), INTERVAL 6 MONTH),
        false,
        'A modern e-commerce platform built with React and Node.js',
        'Full-stack e-commerce solution with payment integration',
        '<p>This is a comprehensive e-commerce platform...</p>',
        '/images/portfolios/ecommerce.jpg',
        'A modern e-commerce platform showcasing my full-stack development skills.',
        NOW(),
        NOW()
    ),
    (
        '30000000-0000-0000-0000-000000000002',
        'Portfolio Website',
        'portfolio-website',
        'Personal Project',
        DATE_SUB(NOW(), INTERVAL 3 MONTH),
        true,
        'My personal portfolio website',
        'A showcase of my projects and skills',
        '<p>This portfolio website demonstrates my web development capabilities...</p>',
        '/images/portfolios/portfolio.jpg',
        'A personal portfolio website built with modern web technologies.',
        NOW(),
        NOW()
    ),
    (
        '30000000-0000-0000-0000-000000000003',
        'Task Management App',
        'task-management-app',
        'Startup Inc',
        DATE_SUB(NOW(), INTERVAL 9 MONTH),
        false,
        'Collaborative task management application',
        'Real-time collaboration features with WebSocket support',
        '<p>A comprehensive task management solution...</p>',
        '/images/portfolios/taskapp.jpg',
        'Built with React, TypeScript, and Node.js for seamless collaboration.',
        NOW(),
        NOW()
    ),
    (
        '30000000-0000-0000-0000-000000000004',
        'Social Media Dashboard',
        'social-media-dashboard',
        'Tech Corp',
        DATE_SUB(NOW(), INTERVAL 12 MONTH),
        false,
        'Analytics dashboard for social media management',
        'Real-time analytics and reporting features',
        '<p>Advanced analytics dashboard with data visualization...</p>',
        '/images/portfolios/dashboard.jpg',
        'A powerful dashboard for managing and analyzing social media presence.',
        NOW(),
        NOW()
    ),
    (
        '30000000-0000-0000-0000-000000000005',
        'Mobile Banking App',
        'mobile-banking-app',
        'Finance Bank',
        DATE_SUB(NOW(), INTERVAL 15 MONTH),
        false,
        'Secure mobile banking application',
        'Banking features with biometric authentication',
        '<p>A secure and user-friendly banking application...</p>',
        '/images/portfolios/banking.jpg',
        'Mobile banking app with advanced security features.',
        NOW(),
        NOW()
    ),
    (
        '30000000-0000-0000-0000-000000000006',
        'Learning Management System',
        'learning-management-system',
        'Education Hub',
        DATE_SUB(NOW(), INTERVAL 18 MONTH),
        false,
        'Online learning platform for courses',
        'Course management and student tracking',
        '<p>Comprehensive LMS with video streaming capabilities...</p>',
        '/images/portfolios/lms.jpg',
        'An intuitive learning management system for online education.',
        NOW(),
        NOW()
    ),
    (
        '30000000-0000-0000-0000-000000000007',
        'Healthcare Portal',
        'healthcare-portal',
        'Medical Center',
        DATE_SUB(NOW(), INTERVAL 21 MONTH),
        false,
        'Patient management and appointment system',
        'HIPAA-compliant healthcare portal',
        '<p>Secure healthcare portal for patient management...</p>',
        '/images/portfolios/healthcare.jpg',
        'A compliant healthcare portal with appointment scheduling.',
        NOW(),
        NOW()
    ),
    (
        '30000000-0000-0000-0000-000000000008',
        'Real Estate Platform',
        'real-estate-platform',
        'Property Group',
        DATE_SUB(NOW(), INTERVAL 24 MONTH),
        false,
        'Property listing and search platform',
        'Advanced search with map integration',
        '<p>Comprehensive real estate platform with virtual tours...</p>',
        '/images/portfolios/realestate.jpg',
        'A modern real estate platform with advanced search features.',
        NOW(),
        NOW()
    ),
    (
        '30000000-0000-0000-0000-000000000009',
        'Food Delivery App',
        'food-delivery-app',
        'Foodie Inc',
        DATE_SUB(NOW(), INTERVAL 27 MONTH),
        false,
        'On-demand food delivery service',
        'Real-time tracking and order management',
        '<p>Food delivery app with live tracking...</p>',
        '/images/portfolios/fooddelivery.jpg',
        'A seamless food delivery experience with real-time updates.',
        NOW(),
        NOW()
    ),
    (
        '30000000-0000-0000-0000-000000000010',
        'Fitness Tracking App',
        'fitness-tracking-app',
        'FitLife',
        DATE_SUB(NOW(), INTERVAL 30 MONTH),
        false,
        'Personal fitness and workout tracker',
        'Workout plans and progress tracking',
        '<p>Comprehensive fitness tracking application...</p>',
        '/images/portfolios/fitness.jpg',
        'Track your fitness journey with detailed analytics.',
        NOW(),
        NOW()
    ),
    (
        '30000000-0000-0000-0000-000000000011',
        'Music Streaming Service',
        'music-streaming-service',
        'SoundWave',
        DATE_SUB(NOW(), INTERVAL 33 MONTH),
        false,
        'Music streaming platform with playlists',
        'High-quality audio streaming',
        '<p>Stream music with personalized recommendations...</p>',
        '/images/portfolios/music.jpg',
        'A music streaming service with curated playlists.',
        NOW(),
        NOW()
    ),
    (
        '30000000-0000-0000-0000-000000000012',
        'Travel Booking Platform',
        'travel-booking-platform',
        'Wanderlust',
        DATE_SUB(NOW(), INTERVAL 36 MONTH),
        false,
        'Hotel and flight booking system',
        'Compare prices and book travel',
        '<p>Book your next adventure with ease...</p>',
        '/images/portfolios/travel.jpg',
        'A comprehensive travel booking platform.',
        NOW(),
        NOW()
    ),
    (
        '30000000-0000-0000-0000-000000000013',
        'Project Management Tool',
        'project-management-tool',
        'Productivity Pro',
        DATE_SUB(NOW(), INTERVAL 39 MONTH),
        false,
        'Team collaboration and project tracking',
        'Kanban boards and time tracking',
        '<p>Manage projects efficiently with team collaboration...</p>',
        '/images/portfolios/project.jpg',
        'Streamline your project management workflow.',
        NOW(),
        NOW()
    ),
    (
        '30000000-0000-0000-0000-000000000014',
        'Weather Forecast App',
        'weather-forecast-app',
        'WeatherTech',
        DATE_SUB(NOW(), INTERVAL 42 MONTH),
        false,
        'Real-time weather forecasts',
        'Detailed weather information and alerts',
        '<p>Get accurate weather forecasts...</p>',
        '/images/portfolios/weather.jpg',
        'Stay informed with detailed weather forecasts.',
        NOW(),
        NOW()
    ),
    (
        '30000000-0000-0000-0000-000000000015',
        'News Aggregator',
        'news-aggregator',
        'NewsHub',
        DATE_SUB(NOW(), INTERVAL 45 MONTH),
        false,
        'Aggregate news from multiple sources',
        'Personalized news feed',
        '<p>Stay updated with curated news...</p>',
        '/images/portfolios/news.jpg',
        'A personalized news aggregator with smart filtering.',
        NOW(),
        NOW()
    ),
    (
        '30000000-0000-0000-0000-000000000016',
        'Chat Application',
        'chat-application',
        'ChatApp Inc',
        DATE_SUB(NOW(), INTERVAL 48 MONTH),
        false,
        'Real-time messaging application',
        'Group chats and file sharing',
        '<p>Connect with friends and colleagues...</p>',
        '/images/portfolios/chat.jpg',
        'A modern chat application with real-time messaging.',
        NOW(),
        NOW()
    ),
    (
        '30000000-0000-0000-0000-000000000017',
        'E-Learning Platform',
        'e-learning-platform',
        'LearnOnline',
        DATE_SUB(NOW(), INTERVAL 51 MONTH),
        false,
        'Interactive online courses',
        'Video lessons and quizzes',
        '<p>Learn new skills with interactive courses...</p>',
        '/images/portfolios/elearning.jpg',
        'An engaging e-learning platform with interactive content.',
        NOW(),
        NOW()
    ),
    (
        '30000000-0000-0000-0000-000000000018',
        'Inventory Management System',
        'inventory-management-system',
        'SupplyChain Co',
        DATE_SUB(NOW(), INTERVAL 54 MONTH),
        false,
        'Warehouse and inventory tracking',
        'Stock management and reporting',
        '<p>Manage inventory efficiently...</p>',
        '/images/portfolios/inventory.jpg',
        'Streamline inventory management with automated tracking.',
        NOW(),
        NOW()
    ),
    (
        '30000000-0000-0000-0000-000000000019',
        'Event Management Platform',
        'event-management-platform',
        'EventPro',
        DATE_SUB(NOW(), INTERVAL 57 MONTH),
        false,
        'Plan and manage events',
        'Ticket sales and attendee management',
        '<p>Organize events seamlessly...</p>',
        '/images/portfolios/event.jpg',
        'A comprehensive event management solution.',
        NOW(),
        NOW()
    ),
    (
        '30000000-0000-0000-0000-000000000020',
        'Blog Platform',
        'blog-platform',
        'BlogSpace',
        DATE_SUB(NOW(), INTERVAL 60 MONTH),
        false,
        'Content management for bloggers',
        'Rich text editor and SEO tools',
        '<p>Create and manage your blog...</p>',
        '/images/portfolios/blog.jpg',
        'A powerful blog platform with advanced features.',
        NOW(),
        NOW()
    )
ON DUPLICATE KEY UPDATE `updated_at` = NOW();
