export type {
    AddParticipantInput,
    Asset,
    ChatMessage,
    ChatParticipant,
    ChatRoom,
    ChatRoomStatus,
    ChatRoomWithParticipants,
    ChatsGetChatRoomMessagesParams,
    ChatsListChatRooms200,
    ChatsListChatRoomsParams,
    CreateChatRoomInput,
    CreateCustomerInput,
    CreateDealInput,
    CreateEmailTemplateInput,
    CreateInquiryInput,
    CreateInquiryResponseInput,
    CreateLeadInput,
    CreatePipelineInput,
    CreatePipelineStageInput,
    Customer,
    CustomerStatus,
    CustomersListCustomers200,
    CustomersListCustomersParams,
    Deal,
    DealStatus,
    DealsListDeals200,
    DealsListDealsParams,
    EmailLog,
    EmailStatus,
    EmailsListEmailLogs200,
    EmailsListEmailLogsParams,
    EmailsListEmailTemplatesParams,
    EmailsSendEmailWithTemplateParams,
    EmailTemplate,
    EmailTemplateCategory,
    ErrorResponse,
    InquiriesListInquiries200,
    InquiriesListInquiriesParams,
    Inquiry,
    InquiryCategory,
    InquiryPriority,
    InquiryResponse,
    InquiryStatus,
    Lead,
    LeadStatus,
    LeadsListLeads200,
    LeadsListLeadsParams,
    PaginationMeta,
    Pipeline,
    PipelineStage,
    Portfolio,
    PortfolioContent,
    PortfoliosListPortfolios200,
    PortfoliosListPortfoliosParams,
    Post,
    PostContent,
    PostsListPosts200,
    PostsListPostsParams,
    SendEmailInput,
    SendMessageInput,
    UpdateCustomerInput,
    UpdateDealInput,
    UpdateEmailTemplateInput,
    UpdateInquiryInput,
    UpdateLeadInput,
    UpdatePipelineInput,
    UpdatePipelineStageInput,
} from "@generated/api.schemas";
export { customInstance } from "@generated/mutator";
export { chats } from "./clients/chats";
export { customers } from "./clients/customers";
export { deals } from "./clients/deals";
export { emails } from "./clients/emails";
export { inquiries } from "./clients/inquiries";
export { leads } from "./clients/leads";
export { pipelines } from "./clients/pipelines";
export { getPortfolioBySlug, listPortfolios, portfolios } from "./clients/portfolios";
export { getPostBySlug, listPosts, posts } from "./clients/posts";
